### ISSUE TITLE
circular reasoning

### ISSUE THREAD

**Issue by rivertrip** [occrp/investigativedashboard.org#9]
Stas closed and redacted issue #8 here, saying to raise it instead at [id.ocrrp.org](https://id.occrp.org/), which says to report it here
![image](https://user-images.githubusercontent.com/62784071/143627664-b7946c23-9643-47e4-bd14-913972c854a9.png)

**Comment by stas** [comment]
@rivertrip this is a place where technical issues are reported. Errors, bugs, and other non-data related issues. Please _file a new request_ on id.occrp.org to get in touch with the OCCRP team.

Thank you!
